### PR TITLE
Transition alert_manager from datazilla to pushlog (hg).

### PR DESCRIPTION
**Pull request by vaibhavmagarwal**

### CODE REVIEW

**Comment by vaibhavmagarwal** [comment]
Run: pip install -r requirements.txt (to install mozci)
Then: python parse_news.py ( I use this command locally, you can use whatever command you use in place of this ).
@jmaher , I have tested it locally, but will advise to test it on your machine and see if everything is ok, and then deploy to the server, since it involves a transition.

**Comment by jmaher** [comment]
Nice.  I will look at this in details a bit later today

**Comment by jmaher** [comment]
The code looks good.  I can test and deploy later today

**Comment by jmaher** [comment]
this is deployed, we will see how this works hands off in production when we get new alerts.

**Pull request merged**
